#!/bin/bash
vers="1.0"

deltemp () {
rm -rf /tmp/filelist.tmp >/dev/null 2>&1
rm -rf /tmp/ffdata.txt >/dev/null 2>&1
}

#Colours
green='\033[92m'
yellow='\e[0;33m'
orange='\e[38;5;166m'
cyan='\e[0;36m'
red='\e[0;31m'
white='\e[0;37m'
outdir=""

function sconvert () {
echo -e "$green""ConvAudio $vers"
echo -e "$yellow""-------------------------"
echo -e "$white""..Supported Conversions..."	
echo -e "$cyan wav$orange ($white Waveform Audio File$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan ape$orange ($white Monkey's Audio Lossless$orange )($white Decode$orange )"
echo -e "$cyan alac$orange ($white Apple Lossless Audio Codec$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan wv$orange ($white WavePack Audio File$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan flac$orange ($white Free Lossless Audio Codec$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan mp3$orange ($white MPEG-2 Audio Layer III$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan m4a$orange ($white MPEG-4 Audio Lossless$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan aif$orange ($white Audio Interchange File$orange )($white Encode$cyan |$white Decode$orange )"
echo -e "$cyan aiff$orange ($white Audio Interchange File Format$orange )($white Encode$cyan |$white Decode$orange )"	
}

function help () {
echo -e "$green""ConvAudio $vers"
echo -e "$yellow""-------------------------"
echo -e "$white""options :"
echo -e "$white""-id $orange(Input Directory)"
echo -e "$white""-ic $orange(Input Conversion (wav,ape,flac,wv,alac,mp3,m4a,aif,aiff)"
echo -e "$white""-oc $orange(Output conversion (wav,flac,wv,alac,mp3,m4a,aif,aiff)"
echo -e "$white""-od $orange(Output Directory (optional)"
echo -e "$white""-r $orange(Remove Original File after conversion)"
echo -e "$white""-sc $orange(Supported Conversions)"
echo -e "$white""-h $orange(This help)"
echo ""
echo -e "$green""Example 1 :$white convaudio -id /my_audio_folder -ic ape -oc flac"
echo -e "$white""($cyan Original files will not be removed & converted files will be place on same input directory$white)"
echo -e "$green""Example 2 :$white convaudio -id /my_audio_folder -ic m4a -oc wav -r"
echo -e "$white""($cyan Original files will be removed & converted files will be place on same input directory$white)"
echo -e "$green""Example 3 :$white convaudio -id /my_audio_folder -ic flac -oc wav -od /root/converted -r"
echo -e "$white""($cyan Original files will not be removed & converted files will be place on desired directory$white)"
exit 0
	
}
function depedency () {
echo -ne "$green""Checking Dependencies ...."
chkffmpg=$(apt-cache policy ffmpeg | grep "Installed" | awk '{print$2}')
if [[ "$chkffmpg" == "(none)" ]]
then
echo -e "$red""Error"
      echo -e "$green""Ffmpeg Missing"
      echo ""
echo -e "$white""Try : apt install ffmpeg"
exit 1
else
echo -e "$green""Done"
fi

}
clear
var="$@"

hlp=$(echo "$var" | grep -w "\-h")
if [[ ! -z "$hlp" ]]
then
help
exit 0
fi

sc=$(echo "$var" | grep -w "\-sc")
if [[ ! -z "$sc" ]]
then
sconvert
exit 0
fi


rfl=$(echo "$var" | grep -w "\-r")
if [[ ! -z "$rfl" ]]
then
rfl="1"
else 
rfl="0"
fi

if [[ -z "$var" ]]
then
depedency
help
fi
echo -e "$green""---------- ConvAudio $vers -----------"
deltemp
depedency

# Check for input directory to search for files
inp=$(echo "$var" | grep -oP '(?<=-id )[^ ]*')
if [[ -z "$inp" ]]
then
echo -e "$white""-No Input Directory was provided"
exit 0
else
if [[ ! -d "$inp" ]]
then
echo -e "$white""-Input Directory :$red $inp$white (Does not Exist)"
exit 0
fi
fi

outdir=$(echo "$var" | grep -oP '(?<=-od )[^ ]*')
if [[ -z "$outdir" ]]
then
outdir=""
else
if [[ ! -d "$outdir" ]]
then
echo -e "$white""-Output Directory :$red $outdir$white (Does not Exist)"
exit 0
fi
fi

flext=$(echo "$var" | grep -oP '(?<=-ic )[^ ]*')
if [[ -z "$flext" ]]
then
echo -e "$white""-No File Extension was provided to convert from"
echo -e "$green""Options :$white ape$green |$white alac$green |$white wv$green |$white wav$green |$white flac$green |$white mp3$green |$white m4a$green |$white aif$green |$white aiff $green with the switch -ic"
exit 0
else
if [ "$flext" != "ape" ] && [ "$flext" != "alac" ] && [ "$flext" != "wv" ] && [ "$flext" != "wav" ] && [ "$flext" != "flac" ] && [ "$flext" != "m4a" ] && [ "$flext" != "aif" ] && [ "$flext" != "aiff" ] && [ "$flext" != "mp3" ]; then
echo -e "$white""-The Files Extension provided is not valid$red ($flext)"
echo -e "$green""Available extensions to split :$white ape$green |$white alac$green |$white wv$green |$white wav$green |$white flac$green |$white mp3$green |$white m4a$green |$white aif$green |$white aiff$green |$white mp3"
exit 0
fi
fi


chkfl=$(find "$inp" -type f -name "*.$flext")
if [[ -z "$chkfl" ]]
then
echo -e "$white""-No files with$green ($flext)$white were found in$cyan $inp"
echo -e "$white""Make sure you check first exists those files extensions on input directory."
exit 0
fi 

outconv=$(echo "$var" | grep -oP '(?<=-oc )[^ ]*')
if [[ -z "$outconv" ]]
then
echo -e "$white""-No Output conversion was provided"
echo -e "$green""Options : ($white alac$green |$white wv$green |$white wav$green |$white flac$green |$white mp3$green |$white m4a$green |$white aif$green |$white aiff ) with the switch$green -oc"
exit 0
else
if [ "$outconv" != "wv" ] && [ "$outconv" != "wav" ] && [ "$outconv" != "flac" ] && [ "$outconv" != "mp3" ] && [ "$outconv" != "m4a" ] && [ "$outconv" != "aif" ] && [ "$outconv" != "aiff" ] && [ "$outconv" != "alac" ]; then
echo -e "$white""-The Output Conversion is not valid ($outconv)"
exit 0
fi
fi
if [[ "$flext" == "$outconv" ]]
then
echo "Are you serious !!!!"
echo "This tool does not convert $flext to $outconv"
echo "Makes no sense :D"
exit 0
fi
echo ""
echo -e "$white""Input Directory :$green $inp"
echo -e "$white""Files to Search :$green $flext"
echo -e "$white""Will be converted to :$green $outconv"
if [[ -z "$outdir" ]]
then
tempdir="Same as Original File"
else
tempdir="$outdir"
fi
echo -e "$white""Output Directory :$green $tempdir"

deltemp

echo -ne "$white""Searching :$green $inp ..."
find "$inp" -type f -name "*.$flext" > /tmp/filelist.tmp
echo -e "$green""Done"

cntfile=$(wc -l /tmp/filelist.tmp | awk '{print$1}')

dirread=""
for i in $(seq "$cntfile")
# 
do
rdfl=$(sed -n "${i}p" /tmp/filelist.tmp)
file=$(echo "$rdfl" | sed 's@.*/@@')
filename=$(echo "$rdfl" | sed 's@.*/@@' | sed 's/\.[^.]*$//')
dirname=$(echo "$rdfl" | sed -r 's|/[^/]+$||')
wrtfile=""
if [[ "$dirread" != "$dirname" ]]
then
echo -e "$orange""Working Dir:$white $dirname"
dirread="$dirname"
fi
if [[ -z "$outdir" ]]
then
outdir="$dirname"
fi


if [[ "$outconv" == "m4a" ]]
then
data="-i /tmp/ffdata.txt -map_metadata 1 -id3v2_version 3 -c:a aac -vn"
elif [[ "$outconv" == "alac" ]]
then
data="-i /tmp/ffdata.txt -map_metadata 1 -id3v2_version 3 -y -vn -acodec alac"
wrtfile="$outdir/$filename.m4a"
else
data="-i /tmp/ffdata.txt -map_metadata 1 -id3v2_version 3"
fi

if [[ -z "$wrtfile" ]]
then
wrtfile="$outdir/$filename.$outconv"
filedisp="$filename.$outconv"
fi


echo -ne "$green""Converting :$white $file$green to$white $filedisp ..."
rm -rf /tmp/ffdata.txt >/dev/null 2>&1
ffmpeg -i "$rdfl" -f ffmetadata /tmp/ffdata.txt >/dev/null 2>&1
ffmpeg -i "$rdfl" $data "$wrtfile" >/dev/null 2>&1

if [[ -f "$outdir/$filename.$outconv" ]]
then
if [[ -s "$outdir/$filename.$outconv" ]]
then
echo -e "$green""Done"
else
echo -e "$red""Error"
rfl="0"
fi
fi
if [[ "$rfl" == "1" ]]
then
rm -rf "$rdfl" >/dev/null 2>&1
fi
done

